import type { ProviderDef } from '@/types';

/**
 * Registry of pre-programmed AI endpoints.
 * Anything OpenAI-compatible is `kind: 'openai'`; the request shape is identical,
 * only the base URL / auth differ. Native providers use their own `kind`.
 */
export const PROVIDERS: ProviderDef[] = [
  /* ---------------------------------------------------------------- */
  /* Frontier labs                                                     */
  /* ---------------------------------------------------------------- */
  {
    id: 'openai',
    name: 'OpenAI (ChatGPT)',
    kind: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://platform.openai.com/api-keys',
    docsUrl: 'https://platform.openai.com/docs/api-reference',
    description: 'GPT-5.x / GPT-4.1 family. Best all-round quality for resume tailoring.',
    supportsJsonMode: true,
    defaultModel: 'gpt-5.2-mini',
    models: [
      { id: 'gpt-5.2', label: 'GPT-5.2', tier: 'flagship', contextWindow: 400000, recommended: true },
      { id: 'gpt-5.2-pro', label: 'GPT-5.2 Pro', tier: 'flagship', contextWindow: 400000 },
      { id: 'gpt-5.2-mini', label: 'GPT-5.2 mini', tier: 'balanced', contextWindow: 400000 },
      { id: 'gpt-5.1', label: 'GPT-5.1', tier: 'flagship', contextWindow: 400000 },
      { id: 'gpt-4.1', label: 'GPT-4.1', tier: 'flagship', contextWindow: 1000000 },
      { id: 'gpt-4.1-mini', label: 'GPT-4.1 mini', tier: 'fast', contextWindow: 1000000 },
      { id: 'gpt-4o', label: 'GPT-4o', tier: 'balanced', contextWindow: 128000 },
      { id: 'gpt-4o-mini', label: 'GPT-4o mini', tier: 'fast', contextWindow: 128000 },
      { id: 'o4-mini', label: 'o4-mini (reasoning)', tier: 'reasoning', contextWindow: 200000 },
      { id: 'o3', label: 'o3 (reasoning)', tier: 'reasoning', contextWindow: 200000 },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    kind: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    auth: 'api-key-header',
    authHeader: 'x-api-key',
    apiVersion: '2023-06-01',
    keyUrl: 'https://console.anthropic.com/settings/keys',
    docsUrl: 'https://docs.anthropic.com/en/api/messages',
    description: 'Claude models excel at nuanced, truthful writing - a great fit for cover letters.',
    supportsJsonMode: true,
    defaultModel: 'claude-sonnet-4-5',
    extraHeaders: { 'anthropic-dangerous-direct-browser-access': 'true' },
    models: [
      { id: 'claude-opus-4-5', label: 'Claude Opus 4.5', tier: 'flagship', contextWindow: 200000, recommended: true },
      { id: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5', tier: 'balanced', contextWindow: 200000, recommended: true },
      { id: 'claude-haiku-4-5', label: 'Claude Haiku 4.5', tier: 'fast', contextWindow: 200000 },
      { id: 'claude-3-7-sonnet-latest', label: 'Claude 3.7 Sonnet', tier: 'balanced', contextWindow: 200000 },
      { id: 'claude-3-5-haiku-latest', label: 'Claude 3.5 Haiku', tier: 'fast', contextWindow: 200000 },
    ],
  },
  {
    id: 'google-gemini',
    name: 'Google Gemini',
    kind: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    auth: 'api-key-query',
    authQueryParam: 'key',
    keyUrl: 'https://aistudio.google.com/app/apikey',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    description: 'Gemini Pro / Flash with very large context and a generous free tier.',
    defaultModel: 'gemini-2.5-flash',
    models: [
      { id: 'gemini-3-pro-preview', label: 'Gemini 3 Pro (preview)', tier: 'flagship', contextWindow: 1000000 },
      { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', tier: 'flagship', contextWindow: 1000000, recommended: true },
      { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', tier: 'fast', contextWindow: 1000000, recommended: true },
      { id: 'gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash Lite', tier: 'fast', contextWindow: 1000000 },
      { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash', tier: 'fast', contextWindow: 1000000 },
    ],
    oauth: {
      authorizeUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/generative-language.retriever'],
      authStyle: 'pkce',
    },
  },
  {
    id: 'google-vertex',
    name: 'Google Vertex AI',
    kind: 'openai',
    baseUrl: 'https://us-central1-aiplatform.googleapis.com/v1/projects/YOUR_PROJECT/locations/us-central1/endpoints/openapi',
    auth: 'api-key-bearer',
    keyUrl: 'https://console.cloud.google.com/apis/credentials',
    docsUrl: 'https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/call-vertex-using-openai-library',
    description: 'Enterprise Gemini + Model Garden. Use an OAuth access token or API key; replace YOUR_PROJECT.',
    defaultModel: 'google/gemini-2.5-pro',
    models: [
      { id: 'google/gemini-2.5-pro', label: 'Gemini 2.5 Pro', tier: 'flagship' },
      { id: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash', tier: 'fast' },
      { id: 'meta/llama-3.3-70b-instruct-maas', label: 'Llama 3.3 70B (MaaS)', tier: 'balanced' },
    ],
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    kind: 'openai',
    baseUrl: 'https://api.x.ai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://console.x.ai',
    docsUrl: 'https://docs.x.ai/docs',
    description: 'Grok models with strong reasoning and a large context window.',
    supportsJsonMode: true,
    defaultModel: 'grok-4',
    models: [
      { id: 'grok-4', label: 'Grok 4', tier: 'flagship', contextWindow: 256000, recommended: true },
      { id: 'grok-3', label: 'Grok 3', tier: 'balanced', contextWindow: 131072 },
      { id: 'grok-3-mini', label: 'Grok 3 mini', tier: 'fast', contextWindow: 131072 },
      { id: 'grok-2-1212', label: 'Grok 2', tier: 'balanced', contextWindow: 131072 },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    kind: 'openai',
    baseUrl: 'https://api.mistral.ai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://console.mistral.ai/api-keys',
    docsUrl: 'https://docs.mistral.ai/api',
    description: 'European frontier models, excellent price/performance.',
    supportsJsonMode: true,
    defaultModel: 'mistral-large-latest',
    models: [
      { id: 'mistral-large-latest', label: 'Mistral Large', tier: 'flagship', contextWindow: 131072, recommended: true },
      { id: 'mistral-medium-latest', label: 'Mistral Medium', tier: 'balanced', contextWindow: 131072 },
      { id: 'mistral-small-latest', label: 'Mistral Small', tier: 'fast', contextWindow: 131072 },
      { id: 'open-mistral-nemo', label: 'Mistral Nemo', tier: 'fast', contextWindow: 131072 },
      { id: 'codestral-latest', label: 'Codestral', tier: 'balanced', contextWindow: 256000 },
      { id: 'ministral-8b-latest', label: 'Ministral 8B', tier: 'fast', contextWindow: 131072 },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    kind: 'cohere',
    baseUrl: 'https://api.cohere.com/v2',
    auth: 'api-key-bearer',
    keyUrl: 'https://dashboard.cohere.com/api-keys',
    docsUrl: 'https://docs.cohere.com/reference/chat',
    description: 'Command models, strong at structured business writing.',
    defaultModel: 'command-a-03-2025',
    models: [
      { id: 'command-a-03-2025', label: 'Command A', tier: 'flagship', contextWindow: 256000, recommended: true },
      { id: 'command-r-plus-08-2024', label: 'Command R+', tier: 'flagship', contextWindow: 128000 },
      { id: 'command-r-08-2024', label: 'Command R', tier: 'balanced', contextWindow: 128000 },
      { id: 'command-r7b-12-2024', label: 'Command R7B', tier: 'fast', contextWindow: 128000 },
    ],
  },

  /* ---------------------------------------------------------------- */
  /* Fast inference clouds                                             */
  /* ---------------------------------------------------------------- */
  {
    id: 'deepseek',
    name: 'DeepSeek',
    kind: 'openai',
    baseUrl: 'https://api.deepseek.com/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://platform.deepseek.com/api_keys',
    docsUrl: 'https://api-docs.deepseek.com',
    description: 'Very cheap, very capable. V4.1 chat and reasoner models.',
    supportsJsonMode: true,
    defaultModel: 'deepseek-chat',
    models: [
      { id: 'deepseek-chat', label: 'DeepSeek V4.1 · chat (auto-updating alias)', tier: 'balanced', contextWindow: 131072, recommended: true },
      { id: 'deepseek-v4.1', label: 'DeepSeek V4.1 (pinned)', tier: 'flagship', contextWindow: 131072, recommended: true },
      { id: 'deepseek-reasoner', label: 'DeepSeek V4.1 · reasoner (auto-updating alias)', tier: 'reasoning', contextWindow: 131072 },
      { id: 'deepseek-v3.2', label: 'DeepSeek V3.2', tier: 'balanced', contextWindow: 131072 },
    ],
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    kind: 'openai',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    auth: 'api-key-bearer',
    keyUrl: 'https://deepinfra.com/dash/api_keys',
    docsUrl: 'https://deepinfra.com/docs/openai_api',
    description: 'Serverless host for hundreds of open models - Llama, Qwen, DeepSeek, Mistral.',
    supportsJsonMode: true,
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', tier: 'balanced', contextWindow: 131072, recommended: true },
      { id: 'deepseek-ai/DeepSeek-V3', label: 'DeepSeek V3', tier: 'balanced', contextWindow: 131072, recommended: true },
      { id: 'Qwen/Qwen2.5-72B-Instruct', label: 'Qwen 2.5 72B', tier: 'balanced', contextWindow: 32768 },
      { id: 'meta-llama/Meta-Llama-3.1-8B-Instruct', label: 'Llama 3.1 8B', tier: 'fast', contextWindow: 131072 },
      { id: 'microsoft/WizardLM-2-8x22B', label: 'WizardLM 2 8x22B', tier: 'flagship', contextWindow: 65536 },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    kind: 'openai',
    baseUrl: 'https://api.groq.com/openai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://console.groq.com/keys',
    docsUrl: 'https://console.groq.com/docs/openai',
    description: 'Fastest inference available - great for interactive bulk tailoring.',
    supportsJsonMode: true,
    defaultModel: 'llama-3.3-70b-versatile',
    models: [
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B Versatile', tier: 'balanced', contextWindow: 131072, recommended: true },
      { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B Instant', tier: 'fast', contextWindow: 131072 },
      { id: 'deepseek-r1-distill-llama-70b', label: 'DeepSeek R1 Distill 70B', tier: 'reasoning', contextWindow: 131072 },
      { id: 'qwen/qwen3-32b', label: 'Qwen 3 32B', tier: 'balanced', contextWindow: 131072 },
      { id: 'openai/gpt-oss-120b', label: 'GPT-OSS 120B', tier: 'flagship', contextWindow: 131072 },
    ],
  },
  {
    id: 'together',
    name: 'Together AI',
    kind: 'openai',
    baseUrl: 'https://api.together.xyz/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://api.together.ai/settings/api-keys',
    docsUrl: 'https://docs.together.ai/reference/chat-completions',
    description: 'Large open-model catalogue with fine-tuning and JSON mode.',
    supportsJsonMode: true,
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', label: 'Llama 3.3 70B Turbo', tier: 'balanced', contextWindow: 131072, recommended: true },
      { id: 'deepseek-ai/DeepSeek-V3', label: 'DeepSeek V3', tier: 'balanced', contextWindow: 131072 },
      { id: 'Qwen/Qwen2.5-72B-Instruct-Turbo', label: 'Qwen 2.5 72B Turbo', tier: 'balanced', contextWindow: 32768 },
      { id: 'mistralai/Mixtral-8x22B-Instruct-v0.1', label: 'Mixtral 8x22B', tier: 'flagship', contextWindow: 65536 },
    ],
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    kind: 'openai',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://fireworks.ai/account/api-keys',
    docsUrl: 'https://docs.fireworks.ai',
    description: 'High-throughput open-model inference with function calling.',
    supportsJsonMode: true,
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    models: [
      { id: 'accounts/fireworks/models/llama-v3p3-70b-instruct', label: 'Llama 3.3 70B', tier: 'balanced', contextWindow: 131072, recommended: true },
      { id: 'accounts/fireworks/models/deepseek-v3', label: 'DeepSeek V3', tier: 'balanced', contextWindow: 131072 },
      { id: 'accounts/fireworks/models/qwen2p5-72b-instruct', label: 'Qwen 2.5 72B', tier: 'balanced', contextWindow: 32768 },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    kind: 'openai',
    baseUrl: 'https://openrouter.ai/api/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://openrouter.ai/keys',
    docsUrl: 'https://openrouter.ai/docs',
    description: 'One key, every model. Great fallback provider and free-model access.',
    supportsJsonMode: true,
    defaultModel: 'openai/gpt-4o-mini',
    extraHeaders: { 'X-Title': 'JobPaal' },
    models: [
      { id: 'openai/gpt-5.2', label: 'GPT-5.2', tier: 'flagship' },
      { id: 'anthropic/claude-sonnet-4.5', label: 'Claude Sonnet 4.5', tier: 'flagship' },
      { id: 'google/gemini-2.5-pro', label: 'Gemini 2.5 Pro', tier: 'flagship' },
      { id: 'openai/gpt-4o-mini', label: 'GPT-4o mini', tier: 'fast', recommended: true },
      { id: 'deepseek/deepseek-chat', label: 'DeepSeek V3', tier: 'balanced', recommended: true },
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B', tier: 'balanced' },
      { id: 'qwen/qwen-2.5-72b-instruct', label: 'Qwen 2.5 72B', tier: 'balanced' },
      { id: 'meta-llama/llama-3.3-70b-instruct:free', label: 'Llama 3.3 70B (free)', tier: 'fast', contextWindow: 65536 },
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    kind: 'openai',
    baseUrl: 'https://api.perplexity.ai',
    auth: 'api-key-bearer',
    keyUrl: 'https://www.perplexity.ai/settings/api',
    docsUrl: 'https://docs.perplexity.ai',
    description: 'Search-grounded Sonar models - useful for company research in cover letters.',
    defaultModel: 'sonar',
    models: [
      { id: 'sonar-pro', label: 'Sonar Pro', tier: 'flagship', recommended: true },
      { id: 'sonar', label: 'Sonar', tier: 'balanced', recommended: true },
      { id: 'sonar-reasoning', label: 'Sonar Reasoning', tier: 'reasoning' },
      { id: 'sonar-reasoning-pro', label: 'Sonar Reasoning Pro', tier: 'reasoning' },
    ],
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    kind: 'openai',
    baseUrl: 'https://api.cerebras.ai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://cloud.cerebras.ai',
    docsUrl: 'https://inference-docs.cerebras.ai',
    description: 'Wafer-scale inference - extremely fast Llama and Qwen models.',
    supportsJsonMode: true,
    defaultModel: 'llama-3.3-70b',
    models: [
      { id: 'llama-3.3-70b', label: 'Llama 3.3 70B', tier: 'balanced', contextWindow: 65536, recommended: true },
      { id: 'llama3.1-8b', label: 'Llama 3.1 8B', tier: 'fast', contextWindow: 32768 },
      { id: 'qwen-3-32b', label: 'Qwen 3 32B', tier: 'balanced', contextWindow: 65536 },
    ],
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    kind: 'openai',
    baseUrl: 'https://api.sambanova.ai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://cloud.sambanova.ai/apis',
    docsUrl: 'https://docs.sambanova.ai',
    description: 'Fast enterprise inference for Llama, DeepSeek and Qwen.',
    defaultModel: 'Meta-Llama-3.3-70B-Instruct',
    models: [
      { id: 'Meta-Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', tier: 'balanced', contextWindow: 131072, recommended: true },
      { id: 'DeepSeek-V3-0324', label: 'DeepSeek V3', tier: 'balanced', contextWindow: 131072 },
      { id: 'Meta-Llama-3.1-8B-Instruct', label: 'Llama 3.1 8B', tier: 'fast', contextWindow: 131072 },
    ],
  },
  {
    id: 'nebius',
    name: 'Nebius AI Studio',
    kind: 'openai',
    baseUrl: 'https://api.studio.nebius.ai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://studio.nebius.ai',
    docsUrl: 'https://docs.nebius.com/studio/inference',
    description: 'European AI cloud with competitive open-model pricing.',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', tier: 'balanced', recommended: true },
      { id: 'Qwen/Qwen2.5-72B-Instruct', label: 'Qwen 2.5 72B', tier: 'balanced' },
      { id: 'deepseek-ai/DeepSeek-V3', label: 'DeepSeek V3', tier: 'balanced' },
    ],
  },
  {
    id: 'novita',
    name: 'Novita AI',
    kind: 'openai',
    baseUrl: 'https://api.novita.ai/v3/openai',
    auth: 'api-key-bearer',
    keyUrl: 'https://novita.ai/settings/key-management',
    docsUrl: 'https://novita.ai/docs',
    description: 'Serverless model hub with a broad open-source catalogue.',
    defaultModel: 'deepseek/deepseek-v3',
    models: [
      { id: 'deepseek/deepseek-v3', label: 'DeepSeek V3', tier: 'balanced', recommended: true },
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B', tier: 'balanced' },
      { id: 'qwen/qwen-2.5-72b-instruct', label: 'Qwen 2.5 72B', tier: 'balanced' },
    ],
  },
  {
    id: 'hyperbolic',
    name: 'Hyperbolic',
    kind: 'openai',
    baseUrl: 'https://api.hyperbolic.xyz/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://app.hyperbolic.xyz/settings',
    docsUrl: 'https://docs.hyperbolic.xyz',
    description: 'Decentralised GPU marketplace with cheap open models.',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', tier: 'balanced', recommended: true },
      { id: 'Qwen/Qwen2.5-72B-Instruct', label: 'Qwen 2.5 72B', tier: 'balanced' },
      { id: 'deepseek-ai/DeepSeek-V3', label: 'DeepSeek V3', tier: 'balanced' },
    ],
  },
  {
    id: 'featherless',
    name: 'Featherless AI',
    kind: 'openai',
    baseUrl: 'https://api.featherless.ai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://featherless.ai/account/api-keys',
    docsUrl: 'https://featherless.ai/docs',
    description: 'Flat-fee access to a huge library of Hugging Face models.',
    defaultModel: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    models: [
      { id: 'meta-llama/Meta-Llama-3.1-8B-Instruct', label: 'Llama 3.1 8B', tier: 'fast', recommended: true },
      { id: 'Qwen/Qwen2.5-72B-Instruct', label: 'Qwen 2.5 72B', tier: 'balanced' },
      { id: 'mistralai/Mistral-Nemo-Instruct-2407', label: 'Mistral Nemo', tier: 'fast' },
    ],
  },
  {
    id: 'chutes',
    name: 'Chutes',
    kind: 'openai',
    baseUrl: 'https://llm.chutes.ai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://chutes.ai/app/api',
    docsUrl: 'https://chutes.ai/docs',
    description: 'Community Bittensor inference with a large model catalogue.',
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    models: [
      { id: 'deepseek-ai/DeepSeek-V3', label: 'DeepSeek V3', tier: 'balanced', recommended: true },
      { id: 'unsloth/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', tier: 'balanced' },
      { id: 'Qwen/Qwen2.5-72B-Instruct', label: 'Qwen 2.5 72B', tier: 'balanced' },
    ],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Router',
    kind: 'openai',
    baseUrl: 'https://router.huggingface.co/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://huggingface.co/settings/tokens',
    docsUrl: 'https://huggingface.co/docs/inference-providers',
    description: 'Routes to the best available inference provider for each model.',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', tier: 'balanced', recommended: true },
      { id: 'Qwen/Qwen2.5-72B-Instruct', label: 'Qwen 2.5 72B', tier: 'balanced' },
      { id: 'deepseek-ai/DeepSeek-V3', label: 'DeepSeek V3', tier: 'balanced' },
    ],
  },
  {
    id: 'github-models',
    name: 'GitHub Models',
    kind: 'openai',
    baseUrl: 'https://models.inference.ai.azure.com',
    auth: 'api-key-bearer',
    keyUrl: 'https://github.com/settings/tokens',
    docsUrl: 'https://docs.github.com/en/github-models',
    description: 'Use a GitHub PAT to access GPT-4o, Llama and more - generous free tier.',
    defaultModel: 'gpt-4o-mini',
    models: [
      { id: 'gpt-4o', label: 'GPT-4o', tier: 'balanced', recommended: true },
      { id: 'gpt-4o-mini', label: 'GPT-4o mini', tier: 'fast' },
      { id: 'Meta-Llama-3.1-70B-Instruct', label: 'Llama 3.1 70B', tier: 'balanced' },
    ],
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    kind: 'openai',
    baseUrl: 'https://YOUR_RESOURCE.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT',
    auth: 'api-key-header',
    authHeader: 'api-key',
    apiVersion: '2024-10-21',
    keyUrl: 'https://portal.azure.com',
    docsUrl: 'https://learn.microsoft.com/azure/ai-services/openai/reference',
    description: 'Enterprise GPT deployments. Replace the resource and deployment placeholders in the base URL.',
    defaultModel: 'gpt-4o',
    models: [
      { id: 'gpt-4o', label: 'gpt-4o (deployment name)', tier: 'balanced', recommended: true },
      { id: 'gpt-4o-mini', label: 'gpt-4o-mini (deployment name)', tier: 'fast' },
      { id: 'gpt-35-turbo', label: 'gpt-35-turbo (deployment name)', tier: 'fast' },
    ],
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare Workers AI',
    kind: 'openai',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT_ID/ai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    docsUrl: 'https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/',
    description: 'Edge inference on Cloudflare GPUs. Replace YOUR_ACCOUNT_ID in the base URL.',
    defaultModel: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    models: [
      { id: '@cf/meta/llama-3.3-70b-instruct-fp8-fast', label: 'Llama 3.3 70B (fast)', tier: 'balanced', recommended: true },
      { id: '@cf/meta/llama-3.1-8b-instruct', label: 'Llama 3.1 8B', tier: 'fast' },
      { id: '@cf/qwen/qwen2.5-coder-32b-instruct', label: 'Qwen 2.5 Coder 32B', tier: 'balanced' },
    ],
  },
  {
    id: 'ai21',
    name: 'AI21 Labs',
    kind: 'openai',
    baseUrl: 'https://api.ai21.com/studio/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://studio.ai21.com/account/api-key',
    docsUrl: 'https://docs.ai21.com',
    description: 'Jamba hybrid SSM models with long context.',
    defaultModel: 'jamba-1.5-large',
    models: [
      { id: 'jamba-1.5-large', label: 'Jamba 1.5 Large', tier: 'flagship', recommended: true },
      { id: 'jamba-1.5-mini', label: 'Jamba 1.5 Mini', tier: 'fast' },
    ],
  },
  {
    id: 'upstage',
    name: 'Upstage Solar',
    kind: 'openai',
    baseUrl: 'https://api.upstage.ai/v1/solar',
    auth: 'api-key-bearer',
    keyUrl: 'https://console.upstage.ai/api-keys',
    docsUrl: 'https://developers.upstage.ai/docs',
    description: 'Compact, fast Solar models with strong instruction following.',
    defaultModel: 'solar-pro',
    models: [
      { id: 'solar-pro', label: 'Solar Pro', tier: 'flagship', recommended: true },
      { id: 'solar-mini', label: 'Solar Mini', tier: 'fast' },
    ],
  },

  /* ---------------------------------------------------------------- */
  /* Asia / regional providers                                         */
  /* ---------------------------------------------------------------- */
  {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    kind: 'openai',
    baseUrl: 'https://api.moonshot.ai/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://platform.moonshot.ai/console/api-keys',
    docsUrl: 'https://platform.moonshot.ai/docs',
    description: 'Kimi models with extremely long context - good for whole-application context.',
    defaultModel: 'kimi-k2-0905-preview',
    models: [
      { id: 'kimi-k2-0905-preview', label: 'Kimi K2', tier: 'flagship', contextWindow: 256000, recommended: true },
      { id: 'kimi-k2-turbo-preview', label: 'Kimi K2 Turbo', tier: 'fast', contextWindow: 256000 },
      { id: 'moonshot-v1-128k', label: 'Moonshot 128k', tier: 'balanced', contextWindow: 128000 },
      { id: 'moonshot-v1-32k', label: 'Moonshot 32k', tier: 'fast', contextWindow: 32768 },
    ],
  },
  {
    id: 'zhipu',
    name: 'Zhipu GLM',
    kind: 'openai',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    auth: 'api-key-bearer',
    keyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    docsUrl: 'https://open.bigmodel.cn/dev/api',
    description: 'GLM-4 models, strong Chinese/English bilingual writing.',
    defaultModel: 'glm-4-plus',
    models: [
      { id: 'glm-4.6', label: 'GLM-4.6', tier: 'flagship', contextWindow: 200000, recommended: true },
      { id: 'glm-4-plus', label: 'GLM-4 Plus', tier: 'flagship' },
      { id: 'glm-4-flash', label: 'GLM-4 Flash', tier: 'fast' },
      { id: 'glm-4-long', label: 'GLM-4 Long', tier: 'balanced', contextWindow: 1000000 },
    ],
  },
  {
    id: 'dashscope',
    name: 'Alibaba Qwen (DashScope)',
    kind: 'openai',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://bailian.console.alibabacloud.com',
    docsUrl: 'https://www.alibabacloud.com/help/en/model-studio',
    description: 'Qwen models via the international OpenAI-compatible endpoint.',
    defaultModel: 'qwen-plus',
    models: [
      { id: 'qwen-max', label: 'Qwen Max', tier: 'flagship', recommended: true },
      { id: 'qwen-plus', label: 'Qwen Plus', tier: 'balanced', recommended: true },
      { id: 'qwen-turbo', label: 'Qwen Turbo', tier: 'fast' },
      { id: 'qwen3-235b-a22b', label: 'Qwen3 235B A22B', tier: 'flagship' },
    ],
  },
  {
    id: 'baidu',
    name: 'Baidu ERNIE',
    kind: 'openai',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    auth: 'api-key-bearer',
    keyUrl: 'https://console.bce.baidu.com/iam/#/iam/apikey/list',
    docsUrl: 'https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html',
    description: 'ERNIE models through Baidu Qianfan V2 OpenAI-compatible API.',
    defaultModel: 'ernie-4.5-turbo-128k',
    models: [
      { id: 'ernie-4.5-turbo-128k', label: 'ERNIE 4.5 Turbo', tier: 'flagship', recommended: true },
      { id: 'ernie-speed-128k', label: 'ERNIE Speed', tier: 'fast' },
    ],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    kind: 'openai',
    baseUrl: 'https://api.minimax.io/v1',
    auth: 'api-key-bearer',
    keyUrl: 'https://platform.minimax.io/user-center/basic-information/interface-key',
    docsUrl: 'https://platform.minimax.io/docs',
    description: 'MiniMax M-series models with long context and fast streaming.',
    defaultModel: 'MiniMax-M2',
    models: [
      { id: 'MiniMax-M2', label: 'MiniMax M2', tier: 'flagship', recommended: true },
      { id: 'MiniMax-Text-01', label: 'MiniMax Text 01', tier: 'balanced', contextWindow: 1000000 },
    ],
  },

  /* ---------------------------------------------------------------- */
  /* Local / self-hosted                                               */
  /* ---------------------------------------------------------------- */
  {
    id: 'ollama',
    name: 'Ollama (local)',
    kind: 'openai',
    baseUrl: 'http://localhost:11434/v1',
    auth: 'none',
    local: true,
    onDevice: true,
    docsUrl: 'https://github.com/ollama/ollama/blob/main/docs/openai.md',
    description: 'Free, private, on-device inference. Make sure Ollama is running locally.',
    defaultModel: 'llama3.2',
    models: [
      { id: 'llama3.2', label: 'Llama 3.2', tier: 'local', recommended: true },
      { id: 'llama3.3', label: 'Llama 3.3 70B', tier: 'local' },
      { id: 'qwen2.5', label: 'Qwen 2.5', tier: 'local', recommended: true },
      { id: 'mistral', label: 'Mistral', tier: 'local' },
      { id: 'phi4', label: 'Phi-4', tier: 'local' },
      { id: 'deepseek-r1', label: 'DeepSeek R1', tier: 'local' },
      { id: 'gemma3', label: 'Gemma 3', tier: 'local' },
      { id: 'llava', label: 'LLaVA (vision)', tier: 'local' },
    ],
  },
  {
    id: 'lmstudio',
    name: 'LM Studio (local)',
    kind: 'openai',
    baseUrl: 'http://localhost:1234/v1',
    auth: 'none',
    local: true,
    onDevice: true,
    docsUrl: 'https://lmstudio.ai/docs/local-server',
    description: 'Private desktop inference. Enable the local server in LM Studio first.',
    defaultModel: 'local-model',
    models: [{ id: 'local-model', label: 'Currently loaded model', tier: 'local', recommended: true }],
  },
  {
    id: 'jan',
    name: 'Jan (local)',
    kind: 'openai',
    baseUrl: 'http://localhost:1337/v1',
    auth: 'none',
    local: true,
    onDevice: true,
    docsUrl: 'https://jan.ai/docs',
    description: 'Open-source ChatGPT alternative that runs entirely offline.',
    defaultModel: 'llama3.2',
    models: [{ id: 'llama3.2', label: 'Llama 3.2', tier: 'local', recommended: true }],
  },
  {
    id: 'llamacpp',
    name: 'llama.cpp server',
    kind: 'openai',
    baseUrl: 'http://localhost:8080/v1',
    auth: 'none',
    local: true,
    onDevice: true,
    docsUrl: 'https://github.com/ggerganov/llama.cpp/tree/master/examples/server',
    description: 'Run any GGUF model with the built-in OpenAI-compatible server.',
    defaultModel: 'default',
    models: [{ id: 'default', label: 'Server default model', tier: 'local', recommended: true }],
  },
  {
    id: 'localai',
    name: 'LocalAI',
    kind: 'openai',
    baseUrl: 'http://localhost:8080/v1',
    auth: 'none',
    local: true,
    onDevice: true,
    docsUrl: 'https://localai.io',
    description: 'Drop-in OpenAI replacement for self-hosted, multi-model setups.',
    defaultModel: 'gpt-4',
    models: [{ id: 'gpt-4', label: 'Configured model', tier: 'local', recommended: true }],
  },
  {
    id: 'vllm',
    name: 'vLLM',
    kind: 'openai',
    baseUrl: 'http://localhost:8000/v1',
    auth: 'none',
    local: true,
    onDevice: true,
    docsUrl: 'https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html',
    description: 'High-throughput serving for any Hugging Face model you host.',
    defaultModel: 'default',
    models: [{ id: 'default', label: 'Served model', tier: 'local', recommended: true }],
  },
  {
    id: 'sglang',
    name: 'SGLang',
    kind: 'openai',
    baseUrl: 'http://localhost:30000/v1',
    auth: 'none',
    local: true,
    onDevice: true,
    docsUrl: 'https://docs.sglang.ai',
    description: 'Fast structured-generation server with OpenAI compatibility.',
    defaultModel: 'default',
    models: [{ id: 'default', label: 'Served model', tier: 'local', recommended: true }],
  },
  {
    id: 'textgenwebui',
    name: 'Text generation web UI',
    kind: 'openai',
    baseUrl: 'http://localhost:5000/v1',
    auth: 'none',
    local: true,
    onDevice: true,
    docsUrl: 'https://github.com/oobabooga/text-generation-webui',
    description: 'oobabooga’s web UI exposes an OpenAI-compatible endpoint.',
    defaultModel: 'default',
    models: [{ id: 'default', label: 'Loaded model', tier: 'local', recommended: true }],
  },
  {
    id: 'koboldcpp',
    name: 'KoboldCpp',
    kind: 'openai',
    baseUrl: 'http://localhost:5001/v1',
    auth: 'none',
    local: true,
    onDevice: true,
    docsUrl: 'https://github.com/LostRuins/koboldcpp',
    description: 'Single-file GGUF runner with an OpenAI-compatible API.',
    defaultModel: 'default',
    models: [{ id: 'default', label: 'Loaded model', tier: 'local', recommended: true }],
  },
  {
    id: 'pollinations',
    name: 'Pollinations (keyless)',
    kind: 'openai',
    baseUrl: 'https://text.pollinations.ai/openai',
    auth: 'none',
    free: true,
    docsUrl: 'https://pollinations.ai',
    description: 'Free community endpoint - no API key required. Rate limited; good for a quick trial.',
    defaultModel: 'openai',
    models: [
      { id: 'openai', label: 'OpenAI (auto)', tier: 'fast', recommended: true },
      { id: 'openai-fast', label: 'OpenAI fast', tier: 'fast' },
      { id: 'mistral', label: 'Mistral', tier: 'fast' },
      { id: 'llama', label: 'Llama', tier: 'fast' },
    ],
  },

  /* ---------------------------------------------------------------- */
  /* Custom endpoints                                                  */
  /* ---------------------------------------------------------------- */
  {
    id: 'custom-openai',
    name: 'Custom OpenAI-compatible endpoint',
    kind: 'openai',
    baseUrl: 'http://localhost:8000/v1',
    auth: 'api-key-bearer',
    custom: true,
    docsUrl: 'https://platform.openai.com/docs/api-reference/chat',
    description: 'Any server that speaks /chat/completions - your own vLLM, gateway, proxy or SaaS.',
    defaultModel: '',
    models: [],
  },
  {
    id: 'custom-none',
    name: 'Custom endpoint (no auth)',
    kind: 'openai',
    baseUrl: 'http://localhost:8080/v1',
    auth: 'none',
    custom: true,
    description: 'An OpenAI-compatible endpoint with no API key (local proxies, tunnels).',
    defaultModel: '',
    models: [],
  },
  {
    id: 'custom-oauth',
    name: 'Custom OAuth 2.0 provider',
    kind: 'openai',
    baseUrl: 'https://api.example.com/v1',
    auth: 'oauth2',
    custom: true,
    description: 'Sign in with any OAuth 2.0 (PKCE) provider that fronts an OpenAI-compatible API.',
    defaultModel: '',
    models: [],
    oauth: {
      authorizeUrl: '',
      tokenUrl: '',
      scopes: [],
      authStyle: 'pkce',
    },
  },
];

export const PROVIDER_MAP: Record<string, ProviderDef> = Object.fromEntries(PROVIDERS.map((p) => [p.id, p]));

export function getProvider(id: string | null | undefined): ProviderDef | undefined {
  if (!id) return undefined;
  return PROVIDER_MAP[id];
}

export function providerGroups(): { label: string; providers: ProviderDef[] }[] {
  const frontier = ['openai', 'anthropic', 'google-gemini', 'google-vertex', 'xai', 'mistral', 'cohere'];
  const clouds = ['deepseek', 'deepinfra', 'groq', 'together', 'fireworks', 'openrouter', 'perplexity', 'cerebras', 'sambanova', 'nebius', 'novita', 'hyperbolic', 'featherless', 'chutes', 'huggingface', 'github-models', 'azure-openai', 'cloudflare', 'ai21', 'upstage'];
  const regional = ['moonshot', 'zhipu', 'dashscope', 'baidu', 'minimax'];
  const local = PROVIDERS.filter((p) => p.local || p.free).map((p) => p.id);
  const custom = PROVIDERS.filter((p) => p.custom).map((p) => p.id);
  const pick = (ids: string[]) => ids.map((id) => PROVIDER_MAP[id]).filter(Boolean);
  return [
    { label: 'Frontier labs', providers: pick(frontier) },
    { label: 'Inference clouds & aggregators', providers: pick(clouds) },
    { label: 'Regional providers', providers: pick(regional) },
    { label: 'Local & keyless', providers: pick(local) },
    { label: 'Custom', providers: pick(custom) },
  ];
}
